name = "yang"
main = "src/index.js"
compatibility_date = "2023-12-01"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.vars]

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"

[env.production]
name = "yang"
routes = [
  { pattern = "docker.signalyc.online", custom_domain = true },
  { pattern = "quay.signalyc.online", custom_domain = true },
  { pattern = "gcr.signalyc.online", custom_domain = true },
  { pattern = "k8s-gcr.signalyc.online", custom_domain = true },
  { pattern = "k8s.signalyc.online", custom_domain = true },
  { pattern = "ghcr.signalyc.online", custom_domain = true },
  { pattern = "cloudsmith.signalyc.online", custom_domain = true },
  { pattern = "ecr.signalyc.online", custom_domain = true },
  { pattern = "docker-staging.signalyc.online", custom_domain = true },
]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "yang-staging"
route = { pattern = "docker-staging.signalyc.online", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
